Add ScalarDB SQL (JDBC) Sample
scalar-labs/scalardb-samples pull request #34
Opened 2023-06-01 07:27 UTC by brfrn169

Please take a look!

2023-06-02 02:43 UTC, komamitsu approved these changes
LGTM! 👍

2023-06-02 05:49 UTC, Torch3333 approved these changes
LGTM, thank you!

2023-06-02 06:01 UTC, josh-wong requested changes
The tutorial is looking good! I've made a few suggestions, so PTAL!

2023-06-02 14:30 UTC, brfrn169 commented on scalardb-sql-jdbc-sample/README.md
> +To download the schema tool, `scalardb-sql-cli-<VERSION>-all.jar`, see the [Releases](https://github.com/scalar-labs/scalardb-sql/releases) of ScalarDB SQL and download the version that you want to u
```suggestion
To download the CLI tool, `scalardb-sql-cli-<VERSION>-all.jar`, see the [Releases](https://github.com/scalar-labs/scalardb-sql/releases) of ScalarDB SQL and download the version that you want to use.
```

2023-06-02 14:56 UTC, brfrn169 commented
@josh-wong Thank you for the suggestions! I have applied them. Please take a look again when you have time!

2023-06-05 02:20 UTC, josh-wong approved these changes
LGTM👍 Thank you!

2023-06-05 02:22 UTC, feeblefakie commented
@reddikih Can you verify if it is OK? (I'll merge it for now, so please create a PR if it needs to be revised.)

2023-06-05 02:22 UTC, feeblefakie approved these changes
LGTM! Thank you!

2023-06-05 02:22 UTC, merged